tasks:
  - name: Install npm dependencies
    init: |
      npm ci
    command: |
      npm run build
      npm run start
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
