name: Feature Reuqest
description: Suggest an idea for this project
title: "[Feature]"
labels: [enhancement]
assignees: shuklaritvik06
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the feature is.
      placeholder: Ex. It would be great if we could do [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Ex. I would like to have an option to do [...]
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Wanna Work on this?
      description: Please check the box if you want to work on this feature.
      options:
        - label: I would like to work on this feature!
          required: false
