name: Close Invalid Issues/PRs
on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]
permissions:
  issues: write
  pull-requests: write
jobs:
  close-invalid:
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest
    steps:
      - name: Close issue
        if: ${{ github.event_name == 'issues' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue close ${{ github.event.issue.html_url }}
      - name: Close PR
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr close ${{ github.event.pull_request.html_url }}
