name: Welcome
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>Thank you for opening an issue</h1>This is a community project, so please be patient while we review your issue. We will get back to you as soon as possible :nerd_face:"
          pr-message: "<h1>Thank you for opening a pull request</h1>This is a community project, so please be patient while we review your pull request. We will get back to you as soon as possible :nerd_face: "
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.webxdao.xyz">Discord</a> and our <a href="https://github.com/WebXDAO">GitHub Organisation</a> Any questions let us know.'
